output: main.o shift.o vigenere.o index_of_coincidence.o
	g++ main.o -o output

main.o: main.cpp
	g++ -c main.cpp

shift.o: shift.cpp
	g++ -c shift.cpp

vigenere.o: vigenere.cpp
	g++ -c vigenere.cpp

index_of_coincidence.o: index_of_coincidence.cpp
	g++ -c index_of_coincidence.cpp


